<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2022/01/14 10:26:41

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:dbname=qdpm_extented_45;host=10.2.4.163',
  'profiler' => false,
  'username' => 'SV-DSI-QDPM-DB',
  'password' => 'SV-DSI-QDPM-DB',
  'name' => 'doctrine',
)),);
