<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2022/01/14 10:26:41

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:dbname=XXX;host=YYY',
  'profiler' => false,
  'username' => 'AAA',
  'password' => 'BBB',
  'name' => 'doctrine',
)),);
