<?php
// auto-generated by sfSecurityConfigHandler
// date: 2022/01/14 11:30:55
$this->security = array (
  'ldap' => 
  array (
    'is_secure' => false,
  ),
  'restorepassword' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
