  
all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:dbname=qdpm_extented_45;host=10.2.4.163'
      profiler: false
      username: AAA    
      password: "<?php echo urlencode('bbb') ; ?>"      
  