<?php

/**
 * ContactsGroupsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactsGroupsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContactsGroupsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContactsGroups');
    }
}