<?php

/**
 * DiscussionsGroupsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DiscussionsGroupsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DiscussionsGroupsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DiscussionsGroups');
    }
}