<?php

/**
 * DiscussionsTypesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DiscussionsTypesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DiscussionsTypesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DiscussionsTypes');
    }
}