<?php

/**
 * EventsPriorityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventsPriorityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventsPriorityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventsPriority');
    }
}