<?php

/**
 * EventsTypesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventsTypesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventsTypesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventsTypes');
    }
}