<?php

/**
 * ExtraFieldsTabsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExtraFieldsTabsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExtraFieldsTabsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExtraFieldsTabs');
    }
}