<?php

/**
 * ExtraFieldsTabs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ExtraFieldsTabs extends BaseExtraFieldsTabs
{
  public static function countByType($bind_type)
  {
    return Doctrine_Core::getTable('ExtraFieldsTabs')->createQuery()->addWhere('bind_type=?',$bind_type)->count();
  }
  
  public static function getChoices($bind_type,$add_empty = true)
  {
    $choices = array();
    
    if($add_empty)
    {
      $choices[''] = '';
    }
    
    $l = Doctrine_Core::getTable('ExtraFieldsTabs')
          ->createQuery()  
          ->addWhere('bind_type=?',$bind_type)        
          ->orderBy('sort_order, name')
          ->fetchArray();
                            
    foreach($l as $v)
    {
      $choices[$v['id']] = $v['name'];
    }
    
    return $choices;
  }
  
  public static function getTabs($bind_type,$sf_user)
  {
    return Doctrine_Core::getTable('ExtraFieldsTabs')
                ->createQuery()
                ->addWhere('bind_type=?',$bind_type)                                
                ->addWhere('find_in_set(' . $sf_user->getAttribute('users_group_id') . ',users_groups_access) or length(users_groups_access)=0 or users_groups_access is null')
                ->orderBy('sort_order, name')
                ->fetchArray();                                                  
  }

  public static function renderTabsHeaders($bind_type,$sf_user)
  {
    $html = '';
    foreach(ExtraFieldsTabs::getTabs($bind_type,$sf_user) as $t)
    {
      $html .= '<li><a href="#extra_tab_' . $t['id'] . '" data-toggle="tab">' . $t['name'] . '</a></li>';  
    }
    
    return $html;
  }
  
  public static function renderTabsContent($bind_type,$object, $sf_user)
  {
    $html = '';
    foreach(ExtraFieldsTabs::getTabs($bind_type,$sf_user) as $t)
    {
      $html .= '<div class="tab-pane fade" id="extra_tab_' . $t['id'] . '">' . ExtraFieldsList::renderFormFiledsByTab($bind_type,$object,$sf_user,$t['id']) . '</div>';  
    }
    
    return $html;
  }
  

  
  public static function renderTabsInDetailsBox($bind_type,$object,$sf_user, $use_fields = '',$extra_values = array())
  {
    if(strlen($use_fields)>0 and $use_fields=='set_off_extra_fields') return '';
    
    $content = '';
     
    foreach(ExtraFieldsTabs::getTabs($bind_type,$sf_user) as $t)
    {    
      $extra_fields = ExtraFieldsList::getFieldsByType($bind_type,$sf_user,false,array('exclude'=>'textarea_wysiwyg,file','tab'=>$t['id']));
      $values = ExtraFieldsList::getValuesList($extra_fields,($object?$object->getId():false));
      
      $html = '';
                 
      foreach($extra_fields as $v)
      {
        if(strlen($use_fields)>0 and !in_array($v['id'],explode(',',$use_fields))) continue;
                
        if(strlen($value = ExtraFieldsList::renderFieldValueByType($v, $values,$extra_values))==0) continue;        
                
        $html .= '
          <tr>
            <th>' . $v['name']. '</th>
            <td>' . $value . '</td>
          </tr>'; 
      }
      
      if(strlen($html)>0)
      {
        $content .= '
          <tr>
            <th><div class="form_tab">' . $t['name'] . '</div></th>            
          </tr>' . $html;
      }
    
    }
    
    return $content;
  }
}