<?php

/**
 * PatternsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PatternsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PatternsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Patterns');
    }
}