<?php

/**
 * ProjectsGroupsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectsGroupsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjectsGroupsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProjectsGroups');
    }
}