<?php

/**
 * ProjectsRolesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectsRolesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjectsRolesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProjectsRoles');
    }
}