<?php

/**
 * TasksToTicketsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TasksToTicketsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TasksToTicketsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TasksToTickets');
    }
}