<?php

/**
 * TasksTimerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TasksTimerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TasksTimerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TasksTimer');
    }
}