<?php

/**
 * TasksToDiscussionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TasksToDiscussionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TasksToDiscussionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TasksToDiscussions');
    }
}