<?php

/**
 * TicketsReports
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TicketsReports extends BaseTicketsReports
{
  public static function getListingOrderChoices()
  {
    $choices = array();
    $choices['projects'] = t::__('Projects');
    $choices['date_added'] = t::__('Date Added');
    $choices['date_last_commented'] = t::__('Date Last Commented');
    $choices['name'] = t::__('Name');
    if(app::countItemsByTable('TicketsPriority')>0) $choices['priority'] = t::__('Priority');
    if(app::countItemsByTable('TicketsStatus')>0)   $choices['status'] = t::__('Status');
    if(app::countItemsByTable('TicketsTypes')>0)    $choices['type'] = t::__('Type');
    if(app::countItemsByTable('TicketsGroups')>0)   $choices['group'] = t::__('Group');
    
    return $choices;
  }
    
  public static function addFiltersToQuery($q,$reports_id,$sf_user=false)
  {
    if($r = Doctrine_Core::getTable('TicketsReports')->find($reports_id))
    { 
      if($r->getDisplayOnlyAssigned()==1)
      {
        $q->addWhere("t.departments_id in (" . implode(',',Departments::getDepartmentIdByUserId($sf_user->getAttribute('id'))). ") or t.users_id='" . $sf_user->getAttribute('id') . "'");
      }
      
      if(strlen($r->getDepartmentsId())>0)
      {
        $q->whereIn('t.departments_id',explode(',',$r->getDepartmentsId()));
      }
      
      if(strlen($r->getTicketsPriorityId())>0)
      {
        $q->whereIn('t.tickets_priority_id',explode(',',$r->getTicketsPriorityId()));
      }
      
      if(strlen($r->getTicketsStatusId())>0)
      {
        $q->whereIn('t.tickets_status_id',explode(',',$r->getTicketsStatusId()));
      }
       
      if(strlen($r->getTicketsTypesId())>0)
      {
        $q->whereIn('t.tickets_types_id',explode(',',$r->getTicketsTypesId()));
      }
        
      if(strlen($r->getTicketsGroupsId())>0)
      {
        $q->whereIn('t.tickets_groups_id',explode(',',$r->getTicketsGroupsId()));
      }
      
      if(strlen($r->getCreatedFrom())>0)
      {
        $q->addWhere('date_format(t.created_at,"%Y-%m-%d")>="' . $r->getCreatedFrom() . '"');
      }      
      if(strlen($r->getCreatedTo())>0)
      {
        $q->addWhere('date_format(t.created_at,"%Y-%m-%d")<="' . $r->getCreatedTo() . '"');
      }
      
      if(strlen($r->getClosedFrom())>0)
      {
        $q->addWhere('date_format(t.closed_date,"%Y-%m-%d")>="' . $r->getClosedFrom() . '"');
      }    
      if(strlen($r->getClosedTo())>0)
      {
        $q->addWhere('date_format(t.closed_date,"%Y-%m-%d")<="' . $r->getClosedTo() . '"');
      }
      
      if($r->getDisplayWithoutProjects()==1)
      {
        $q->addWhere('t.projects_id is null');
      }
      
      if(strlen($r->getExtraFields())>0)
      {            
        $extra_fields = unserialize($r->getExtraFields());                        
        $count_e = 0;
                                
        foreach($extra_fields as $efId=>$values)
        {
          $filter_sql_array = array();
          foreach($values as $id)
          {
            $filter_sql_array[] = 'find_in_set("' . $id . '",REPLACE(e' . ($count_e>0?$count_e:''). '.value,"\n",","))';
          }
                  
          $sql = '(SELECT COUNT(*) FROM ExtraFieldsList efl' . $efId . ' WHERE  (' . implode(' OR ',$filter_sql_array) . ') AND efl' . $efId . '.bind_id=t.id AND efl' . $efId . '.extra_fields_id="' . $efId . '")>0';
                                                      
          $q->addWhere($sql);
          
          if($count_e==0)
          {
            $count_e=2;
          }
          else
          {
            $count_e++;
          }
        }
      }
      
      
      if(strlen($r->getCreatedBy())>0)
      {
        $q->whereIn('t.users_id',explode(',',$r->getCreatedBy()));
      }
                
      if(strlen($r->getProjectsPriorityId())>0)
      {
        $q->whereIn('p.projects_priority_id',explode(',',$r->getProjectsPriorityId()));
      }
      
      if(strlen($r->getProjectsStatusId())>0)
      {
        $q->whereIn('p.projects_status_id',explode(',',$r->getProjectsStatusId()));
      }
       
      if(strlen($r->getProjectsTypeId())>0)
      {
        $q->whereIn('p.projects_types_id',explode(',',$r->getProjectsTypeId()));
      }
        
      if(strlen($r->getProjectsGroupsId())>0)
      {
        $q->whereIn('p.projects_groups_id',explode(',',$r->getProjectsGroupsId()));
      }
                
      if(strlen($r->getProjectsId())>0)
      {
        $q->whereIn('p.id',explode(',',$r->getProjectsId()));
      }
      
      $q = Tickets::getListingOrderByType($q,$r->getListingOrder());
                                    
    }
                  
    return $q;  
  }
}