<?php

/**
 * TicketsPriorityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TicketsPriorityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TicketsPriorityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TicketsPriority');
    }
}