<?php

/**
 * TicketsGroupsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TicketsGroupsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TicketsGroupsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TicketsGroups');
    }
}