<?php

/**
 * UsersListingsOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsersListingsOrderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsersListingsOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsersListingsOrder');
    }
}