<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Tickets', 'doctrine');

/**
 * BaseTickets
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $departments_id
 * @property integer $tickets_types_id
 * @property integer $tickets_status_id
 * @property integer $tickets_priority_id
 * @property integer $tickets_groups_id
 * @property string $name
 * @property string $description
 * @property integer $users_id
 * @property integer $projects_id
 * @property timestamp $created_at
 * @property string $user_name
 * @property string $user_email
 * @property string $message_id
 * @property integer $in_trash
 * @property integer $in_trash_date
 * @property integer $last_comment_date
 * @property timestamp $closed_date
 * @property TicketsGroups $TicketsGroups
 * @property TicketsPriority $TicketsPriority
 * @property Departments $Departments
 * @property TicketsTypes $TicketsTypes
 * @property TicketsStatus $TicketsStatus
 * @property Users $Users
 * @property Projects $Projects
 * @property Doctrine_Collection $Tasks
 * @property Doctrine_Collection $TasksToTickets
 * @property Doctrine_Collection $TicketsComments
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method integer             getDepartmentsId()       Returns the current record's "departments_id" value
 * @method integer             getTicketsTypesId()      Returns the current record's "tickets_types_id" value
 * @method integer             getTicketsStatusId()     Returns the current record's "tickets_status_id" value
 * @method integer             getTicketsPriorityId()   Returns the current record's "tickets_priority_id" value
 * @method integer             getTicketsGroupsId()     Returns the current record's "tickets_groups_id" value
 * @method string              getName()                Returns the current record's "name" value
 * @method string              getDescription()         Returns the current record's "description" value
 * @method integer             getUsersId()             Returns the current record's "users_id" value
 * @method integer             getProjectsId()          Returns the current record's "projects_id" value
 * @method timestamp           getCreatedAt()           Returns the current record's "created_at" value
 * @method string              getUserName()            Returns the current record's "user_name" value
 * @method string              getUserEmail()           Returns the current record's "user_email" value
 * @method string              getMessageId()           Returns the current record's "message_id" value
 * @method integer             getInTrash()             Returns the current record's "in_trash" value
 * @method integer             getInTrashDate()         Returns the current record's "in_trash_date" value
 * @method integer             getLastCommentDate()     Returns the current record's "last_comment_date" value
 * @method timestamp           getClosedDate()          Returns the current record's "closed_date" value
 * @method TicketsGroups       getTicketsGroups()       Returns the current record's "TicketsGroups" value
 * @method TicketsPriority     getTicketsPriority()     Returns the current record's "TicketsPriority" value
 * @method Departments         getDepartments()         Returns the current record's "Departments" value
 * @method TicketsTypes        getTicketsTypes()        Returns the current record's "TicketsTypes" value
 * @method TicketsStatus       getTicketsStatus()       Returns the current record's "TicketsStatus" value
 * @method Users               getUsers()               Returns the current record's "Users" value
 * @method Projects            getProjects()            Returns the current record's "Projects" value
 * @method Doctrine_Collection getTasks()               Returns the current record's "Tasks" collection
 * @method Doctrine_Collection getTasksToTickets()      Returns the current record's "TasksToTickets" collection
 * @method Doctrine_Collection getTicketsComments()     Returns the current record's "TicketsComments" collection
 * @method Tickets             setId()                  Sets the current record's "id" value
 * @method Tickets             setDepartmentsId()       Sets the current record's "departments_id" value
 * @method Tickets             setTicketsTypesId()      Sets the current record's "tickets_types_id" value
 * @method Tickets             setTicketsStatusId()     Sets the current record's "tickets_status_id" value
 * @method Tickets             setTicketsPriorityId()   Sets the current record's "tickets_priority_id" value
 * @method Tickets             setTicketsGroupsId()     Sets the current record's "tickets_groups_id" value
 * @method Tickets             setName()                Sets the current record's "name" value
 * @method Tickets             setDescription()         Sets the current record's "description" value
 * @method Tickets             setUsersId()             Sets the current record's "users_id" value
 * @method Tickets             setProjectsId()          Sets the current record's "projects_id" value
 * @method Tickets             setCreatedAt()           Sets the current record's "created_at" value
 * @method Tickets             setUserName()            Sets the current record's "user_name" value
 * @method Tickets             setUserEmail()           Sets the current record's "user_email" value
 * @method Tickets             setMessageId()           Sets the current record's "message_id" value
 * @method Tickets             setInTrash()             Sets the current record's "in_trash" value
 * @method Tickets             setInTrashDate()         Sets the current record's "in_trash_date" value
 * @method Tickets             setLastCommentDate()     Sets the current record's "last_comment_date" value
 * @method Tickets             setClosedDate()          Sets the current record's "closed_date" value
 * @method Tickets             setTicketsGroups()       Sets the current record's "TicketsGroups" value
 * @method Tickets             setTicketsPriority()     Sets the current record's "TicketsPriority" value
 * @method Tickets             setDepartments()         Sets the current record's "Departments" value
 * @method Tickets             setTicketsTypes()        Sets the current record's "TicketsTypes" value
 * @method Tickets             setTicketsStatus()       Sets the current record's "TicketsStatus" value
 * @method Tickets             setUsers()               Sets the current record's "Users" value
 * @method Tickets             setProjects()            Sets the current record's "Projects" value
 * @method Tickets             setTasks()               Sets the current record's "Tasks" collection
 * @method Tickets             setTasksToTickets()      Sets the current record's "TasksToTickets" collection
 * @method Tickets             setTicketsComments()     Sets the current record's "TicketsComments" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTickets extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tickets');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('departments_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('tickets_types_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('tickets_status_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('tickets_priority_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('tickets_groups_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('users_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('projects_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('user_name', 'string', 64, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 64,
             ));
        $this->hasColumn('user_email', 'string', 64, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 64,
             ));
        $this->hasColumn('message_id', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('in_trash', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('in_trash_date', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('last_comment_date', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('closed_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TicketsGroups', array(
             'local' => 'tickets_groups_id',
             'foreign' => 'id'));

        $this->hasOne('TicketsPriority', array(
             'local' => 'tickets_priority_id',
             'foreign' => 'id'));

        $this->hasOne('Departments', array(
             'local' => 'departments_id',
             'foreign' => 'id'));

        $this->hasOne('TicketsTypes', array(
             'local' => 'tickets_types_id',
             'foreign' => 'id'));

        $this->hasOne('TicketsStatus', array(
             'local' => 'tickets_status_id',
             'foreign' => 'id'));

        $this->hasOne('Users', array(
             'local' => 'users_id',
             'foreign' => 'id'));

        $this->hasOne('Projects', array(
             'local' => 'projects_id',
             'foreign' => 'id'));

        $this->hasMany('Tasks', array(
             'local' => 'id',
             'foreign' => 'tickets_id'));

        $this->hasMany('TasksToTickets', array(
             'local' => 'id',
             'foreign' => 'tickets_id'));

        $this->hasMany('TicketsComments', array(
             'local' => 'id',
             'foreign' => 'tickets_id'));
    }
}