<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Contacts', 'doctrine');

/**
 * BaseContacts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $email
 * @property integer $contacts_groups_id
 * @property ContactsGroups $ContactsGroups
 * 
 * @method integer        getId()                 Returns the current record's "id" value
 * @method string         getName()               Returns the current record's "name" value
 * @method string         getEmail()              Returns the current record's "email" value
 * @method integer        getContactsGroupsId()   Returns the current record's "contacts_groups_id" value
 * @method ContactsGroups getContactsGroups()     Returns the current record's "ContactsGroups" value
 * @method Contacts       setId()                 Sets the current record's "id" value
 * @method Contacts       setName()               Sets the current record's "name" value
 * @method Contacts       setEmail()              Sets the current record's "email" value
 * @method Contacts       setContactsGroupsId()   Sets the current record's "contacts_groups_id" value
 * @method Contacts       setContactsGroups()     Sets the current record's "ContactsGroups" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContacts extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contacts');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 64, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 64,
             ));
        $this->hasColumn('contacts_groups_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ContactsGroups', array(
             'local' => 'contacts_groups_id',
             'foreign' => 'id'));
    }
}