<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ContactsGroups', 'doctrine');

/**
 * BaseContactsGroups
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $sort_order
 * @property Doctrine_Collection $Contacts
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getName()       Returns the current record's "name" value
 * @method integer             getSortOrder()  Returns the current record's "sort_order" value
 * @method Doctrine_Collection getContacts()   Returns the current record's "Contacts" collection
 * @method ContactsGroups      setId()         Sets the current record's "id" value
 * @method ContactsGroups      setName()       Sets the current record's "name" value
 * @method ContactsGroups      setSortOrder()  Sets the current record's "sort_order" value
 * @method ContactsGroups      setContacts()   Sets the current record's "Contacts" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContactsGroups extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contacts_groups');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 64, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 64,
             ));
        $this->hasColumn('sort_order', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Contacts', array(
             'local' => 'id',
             'foreign' => 'contacts_groups_id'));
    }
}