<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TasksToTickets', 'doctrine');

/**
 * BaseTasksToTickets
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $tasks_id
 * @property integer $tickets_id
 * @property Tasks $Tasks
 * @property Tickets $Tickets
 * 
 * @method integer        getId()         Returns the current record's "id" value
 * @method integer        getTasksId()    Returns the current record's "tasks_id" value
 * @method integer        getTicketsId()  Returns the current record's "tickets_id" value
 * @method Tasks          getTasks()      Returns the current record's "Tasks" value
 * @method Tickets        getTickets()    Returns the current record's "Tickets" value
 * @method TasksToTickets setId()         Sets the current record's "id" value
 * @method TasksToTickets setTasksId()    Sets the current record's "tasks_id" value
 * @method TasksToTickets setTicketsId()  Sets the current record's "tickets_id" value
 * @method TasksToTickets setTasks()      Sets the current record's "Tasks" value
 * @method TasksToTickets setTickets()    Sets the current record's "Tickets" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTasksToTickets extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tasks_to_tickets');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('tasks_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('tickets_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tasks', array(
             'local' => 'tasks_id',
             'foreign' => 'id'));

        $this->hasOne('Tickets', array(
             'local' => 'tickets_id',
             'foreign' => 'id'));
    }
}