<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('WikiHistory', 'doctrine');

/**
 * BaseWikiHistory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $wiki_id
 * @property integer $projects_id
 * @property string $name
 * @property string $description
 * @property integer $users_id
 * @property timestamp $created_at
 * @property Wiki $Wiki
 * @property Projects $Projects
 * @property Users $Users
 * 
 * @method integer     getId()          Returns the current record's "id" value
 * @method integer     getWikiId()      Returns the current record's "wiki_id" value
 * @method integer     getProjectsId()  Returns the current record's "projects_id" value
 * @method string      getName()        Returns the current record's "name" value
 * @method string      getDescription() Returns the current record's "description" value
 * @method integer     getUsersId()     Returns the current record's "users_id" value
 * @method timestamp   getCreatedAt()   Returns the current record's "created_at" value
 * @method Wiki        getWiki()        Returns the current record's "Wiki" value
 * @method Projects    getProjects()    Returns the current record's "Projects" value
 * @method Users       getUsers()       Returns the current record's "Users" value
 * @method WikiHistory setId()          Sets the current record's "id" value
 * @method WikiHistory setWikiId()      Sets the current record's "wiki_id" value
 * @method WikiHistory setProjectsId()  Sets the current record's "projects_id" value
 * @method WikiHistory setName()        Sets the current record's "name" value
 * @method WikiHistory setDescription() Sets the current record's "description" value
 * @method WikiHistory setUsersId()     Sets the current record's "users_id" value
 * @method WikiHistory setCreatedAt()   Sets the current record's "created_at" value
 * @method WikiHistory setWiki()        Sets the current record's "Wiki" value
 * @method WikiHistory setProjects()    Sets the current record's "Projects" value
 * @method WikiHistory setUsers()       Sets the current record's "Users" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWikiHistory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('wiki_history');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('wiki_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('projects_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 64, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 64,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('users_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Wiki', array(
             'local' => 'wiki_id',
             'foreign' => 'id'));

        $this->hasOne('Projects', array(
             'local' => 'projects_id',
             'foreign' => 'id'));

        $this->hasOne('Users', array(
             'local' => 'users_id',
             'foreign' => 'id'));
    }
}