<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ExtraFieldsTabs', 'doctrine');

/**
 * BaseExtraFieldsTabs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $bind_type
 * @property string $users_groups_access
 * @property integer $sort_order
 * @property Doctrine_Collection $ExtraFields
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method string              getName()                Returns the current record's "name" value
 * @method string              getBindType()            Returns the current record's "bind_type" value
 * @method string              getUsersGroupsAccess()   Returns the current record's "users_groups_access" value
 * @method integer             getSortOrder()           Returns the current record's "sort_order" value
 * @method Doctrine_Collection getExtraFields()         Returns the current record's "ExtraFields" collection
 * @method ExtraFieldsTabs     setId()                  Sets the current record's "id" value
 * @method ExtraFieldsTabs     setName()                Sets the current record's "name" value
 * @method ExtraFieldsTabs     setBindType()            Sets the current record's "bind_type" value
 * @method ExtraFieldsTabs     setUsersGroupsAccess()   Sets the current record's "users_groups_access" value
 * @method ExtraFieldsTabs     setSortOrder()           Sets the current record's "sort_order" value
 * @method ExtraFieldsTabs     setExtraFields()         Sets the current record's "ExtraFields" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExtraFieldsTabs extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('extra_fields_tabs');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 64, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 64,
             ));
        $this->hasColumn('bind_type', 'string', 64, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 64,
             ));
        $this->hasColumn('users_groups_access', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('sort_order', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ExtraFields', array(
             'local' => 'id',
             'foreign' => 'extra_fields_tabs_id'));
    }
}